### ISSUE TITLE
Multiple character sheets merges weapon list

### ISSUE THREAD

**Issue by carleshf** [matsavage/DND-5e-LaTeX-Character-Template#12]
Hi! Thanks for you effort building this!

I am trying to put three character sheets together but the weapon list in the first page gets merged. Any way you could point me how to clear this _list_ at the beginning of a new character sheet?

While I know how to write a document using LaTeX, this is my first time dealing with its underlining mechanics. I understand that the issue are the `AddWeapon` and `WeaponsHeld`. So, I tried using `\WeaponsHeld{}` before writing the weapons' list but it gives me a strange error of no line to end. Any help is welcome!

Thanks!
~Carles

**Comment by matsavage** [comment]
looks great :+1:
