### ISSUE TITLE
Add option to specify expended spell slots

### ISSUE THREAD

**Issue by Ambossmann** [matsavage/DND-5e-LaTeX-Character-Template#88]
It would be pretty useful if it was possible to specify the expended spell slots directly in the LaTeX. This would allow using only the template together with some form of live preview to manage your character sheet during play.

**Comment by matsavage** [comment]
I’m not 100% sure what you mean, like a fillable text box on the rendered PDF?

**Comment by Ambossmann** [comment]
No, I mean a simple text like with `\FirstLevelSpellSlotsTotal{<value>}`. This would be set with something like `\FirstLevelSpellSlotsExpended{<value>}`. As far as I can tell, the "Slots Expended" field is the only one in the entire character sheet that can't be set in the LaTeX, so it would make sense to add it. Of course, this would have to be implemented for all spell slot levels and not just for the first.

**Comment by matsavage** [comment]
Oh, that's not a huge job, just a copy paste of the total to a new extended field to the side, I'd be happy to accept a PR if you were able to do that, or I can have a look, but it won't be for a little while, as work is taking up a lot of my time at the moment
